[package]
name = "examples"
version = "0.0.0"
edition = "2024"
publish = false
autoexamples = false

[[example]]
name = "dqn_cartpole"
path = "examples/dqn_cartpole.rs"

[[example]]
name = "ppo_bench"
path = "examples/ppo_bench.rs"

[[example]]
name = "ppo_cartpole"
path = "examples/ppo_cartpole.rs"

[[example]]
name = "sac_cartpole"
path = "examples/sac_cartpole.rs"

[[example]]
name = "ppo_mujoco"
path = "examples/ppo_mujoco.rs"
required-features = ["mujoco-environment"]

[[example]]
name = "a2c_mujoco"
path = "examples/a2c_mujoco.rs"
required-features = ["mujoco-environment"]

[[example]]
name = "sac_mujoco"
path = "examples/sac_mujoco.rs"
required-features = ["mujoco-environment"]

[[example]]
name = "ddpg_mujoco"
path = "examples/ddpg_mujoco.rs"
required-features = ["mujoco-environment"]

[[example]]
name = "td3_mujoco"
path = "examples/td3_mujoco.rs"
required-features = ["mujoco-environment"]

[[example]]
name = "rendered_lunar_lander_ppo"
path = "examples/rendered_lunar_lander_ppo.rs"
required-features = ["rendering"]

[[example]]
name = "ppo_atari"
path = "examples/ppo_atari.rs"
required-features = ["atari-environment"]

[[example]]
name = "ppo_atari_play"
path = "examples/ppo_atari_play.rs"
required-features = ["atari-environment", "rendering"]

[dependencies]
modurl = { version = "0.1.0", path = "../.." }
modurl_ale = { version = "0.1.0", path = "../modurl_ale", optional = true }
modurl_gym = { version = "0.1.0", path = "../modurl_gym" }
modurl_logger = { version = "0.1.0", path = "../modurl_logger" }
modurl_mojoco = { version = "0.1.0", path = "../modurl_mojoco" }
candle-core = "0.11.0"
candle-nn = "0.11.0"

[features]
default = []
ant = ["mujoco-environment"]
atari-environment = ["dep:modurl_ale"]
half-cheetah = ["mujoco-environment"]
hopper = ["mujoco-environment"]
mujoco-environment = []
walker2d = ["mujoco-environment"]
cuda = ["candle-core/cuda"]
cudnn = ["cuda", "candle-core/cudnn"]
metal = ["candle-core/metal"]
multithreading = ["modurl/multithreading"]
rendering = ["modurl_ale?/rendering", "modurl_gym/rendering", "modurl_mojoco/rendering"]
